<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv [
  <!ELEMENT cv (nom, idiomes, llengues)>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT idiomes (idioma*)>
  <!ELEMENT idioma (#PCDATA)>
  <!ELEMENT llengues (llengua*)>
  <!ELEMENT llengua (#PCDATA)>
  <!ATTLIST llengua identificador ID #REQUIRED>
  <!ATTLIST idioma nivell (baix | mitjà | alt) "mitjà">
  <!ATTLIST idioma codiPais IDREF #REQUIRED>
]>
<cv>
  <nom>Desmond Miles</nom>
  <idiomes>
    <idioma codiPais="fr" nivell="baix">Francès</idioma>
    <idioma codiPais="en">Anglès</idioma>
    <idioma codiPais="it">Italià</idioma>
  </idiomes>
  <llengues>
    <llengua identificador="fr">Francès</llengua>
    <llengua identificador="en">Anglès</llengua>
    <llengua identificador="it">Italià</llengua>
    <llengua identificador="es">Spain</llengua>
  </llengues>
</cv>