=== irevm/xml_examples/xsd/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="client" type="client"/>
        <xs:element name="concepte" type="concepte" minOccurs="0" maxOccurs="unbounded"/>
        <!--Per definir elements amb atributs i contingut de tipus text hi ha diferents opcions. Una, és emprar mixed="true", però d'aquesta manera no podem validar el tipus del text-->
        <!-- <xs:element name="impost">
          <xs:complexType mixed="true">
            <xs:attribute name="nom" type="xs:string"/>
          </xs:complexType>
        </xs:element> -->

        <!--Una altra opció és emprar un simpleContent. Bàsicament és com definir un tipus simple però fer una extensió i afegir-hi un atribut, fet que el converteix en element compost. -->
        <xs:element name="impost">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="nom" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="totalFactura" type="totalFactura"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="client">
    <xs:sequence>
      <xs:element name="nom"/>
      <xs:element name="CIF"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="concepte">
    <xs:sequence>
      <xs:element name="descripcio"/>
      <xs:element name="import"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="totalFactura">
    <xs:attribute name="euros" type="xs:decimal"/>
  </xs:complexType>
</xs:schema>

=== irevm/xml_examples/xsd/exemple_xsd2.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="factura.xsd">
  <numero>1</numero>
  <client>
    <nom>Ediciones Paraninfo S.A.</nom>
    <CIF>A81461477</CIF>
  </client>
  <concepte>
    <descripcio>Imprempta</descripcio>
    <import>1000</import>
  </concepte>
  <concepte>
    <descripcio>Maquetaci√≥</descripcio>
    <import>500.50</import>
  </concepte>
  <impost nom="IVA">PENDENT</impost>
  <totalFactura euros="1500.50"/>
</factura>
